checksumBehavior: update

compressionLevel: mixed

defaultLanguageName: node

enableColors: true

enableGlobalCache: true

enableHyperlinks: true

enableTimers: true

ignorePath: false

nmMode: hardlinks-global

nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

progressBarStyle: jack

yarnPath: ./.yarn/releases/yarn-3.0.0.cjs
