cacheFolder: ~/.cache/yarn/cache_for_yarn-3.0.0

checksumBehavior: update

compressionLevel: mixed

defaultLanguageName: node

enableColors: true

enableGlobalCache: true

enableHyperlinks: true

enableTimers: true

globalFolder: ~/.cache/yarn/global

ignorePath: false

nmMode: hardlinks-global

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

progressBarStyle: jack

yarnPath: ./.yarn/releases/yarn-3.0.0.cjs
