yarnPath: ".yarn/releases/yarn-3.0.0.cjs" 

cacheFolder: "~/.cache/yarn/cache_for_yarn-3.0.0"

changesetIgnorePatterns:
  "**/*.test.{js,ts}"

checksumBehavior: "update"

compressionLevel: "mixed"

defaultLanguageName: "node"

deferredVersionFolder: "~/.cache/yarn/versions"

enableColors: true

enableGlobalCache: true

enableHyperlinks: true

enableTimers: true

globalFolder: "~/.cache/yarn/global"

nmMode: "hardlinks-global"

progressBarStyle: "jack"

nodeLinker: "node-modules"
