yarnPath: "./.yarn/releases/yarn-3.0.0.cjs" 

ignorePath: false

cacheFolder: "~/.cache/yarn/cache_for_yarn-3.0.0"

checksumBehavior: "update"

compressionLevel: "mixed"

defaultLanguageName: "node"

enableColors: true

enableGlobalCache: true

enableHyperlinks: true

enableTimers: true

globalFolder: "~/.cache/yarn/global"

nmMode: "hardlinks-global"

progressBarStyle: "jack"

nodeLinker: "node-modules"
